name: Documentation Generation

on:
  push:
    branches:
    - master

jobs:
  generate_doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    - name: Generate Actions Documentation
      uses: ./github-actions
      with:
        github_token: '${{ github.token }}'
